// imported modules
import { useEffect } from 'react';
import { connect } from 'react-redux';
import Head from 'next/head'
import Nav from 'components/Nav';
import cartActions from 'redux/cart/cartActions';

// create component
const Layout = ({ children, themeMode }) => {

   // effect after rendering
   useEffect(() => {
      cartActions.loadProducts();
   }, [])

   // render
   return (
      <>
         {/* head */}
         <Head>
            <title>Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         {/* body */}
         <div
            className={`${themeMode} relative bg-default min-h-screen 
            text-default font-raleway md:text-sm text-xs md:pt-20 pt-16 md:pb-60 pb-48`}
         >

            {/* navigation */}
            <Nav />

            {/* pages */}
            {children}

            {/* footer */}
            <div className="absolute bottom-0 md:h-60 h-48 w-full md:mt-20 mt-10 bg-paper">

            </div>
         </div>
      </>
   )
}

// state mapping to pass properties to component
const mapStateToProps = (state) => ({
   themeMode: state.themeState.themeMode
})

// export component
export default connect(mapStateToProps)(Layout);
