// imported modules
import { connect } from 'react-redux';
import Head from 'next/head'
import Nav from 'components/Nav';

// create component
const Layout = ({ children, themeMode }) => {

   // render
   return (
      <>
         {/* head */}
         <Head>
            <title>Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         {/* body */}
         <div
            className={`${themeMode} bg-default min-h-screen
            text-default font-raleway md:text-sm text-xs md:pt-20 pt-16`}
         >

            {/* navigation */}
            <Nav />

            {/* pages */}
            {children}

         </div>
      </>
   )
}

// state mapping to pass properties to component
const mapStateToProps = (state) => ({
   themeMode: state.themeState.themeMode
})

// export component
export default connect(mapStateToProps)(Layout);
