// imported modules
import { useEffect } from 'react';
import { connect } from 'react-redux';
import Head from 'next/head'
import Nav from './Nav';
import Footer from './Footer';
import cartActions from 'redux/cart/cartActions';
import themeActions from 'redux/theme/themeActions';

// create component
const Layout = ({ children, theme }) => {

   // effect after rendering
   useEffect(() => {
      cartActions.loadProducts();
      themeActions.loadTheme();
   }, [])

   // render
   return (
      <>
         {/* head */}
         <Head>
            <title>E-Commerce</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         {/* body */}
         <div
            className={`${theme} relative bg-default min-h-screen 
            text-default font-raleway md:text-sm text-xs`}
         >

            {/* navigation */}
            <Nav />

            {/* pages */}
            {children}

            {/* footer */}
            <Footer />
         </div>
      </>
   )
}

// state mapping to pass properties to component
const mapStateToProps = (state) => ({
   theme: state.themeState.theme
})

// export component
export default connect(mapStateToProps)(Layout);
